Repository UbiState/ubicoin, pull requests merged in 2020-05, with the labels that each got.

#3 Update blockchain size
  doc/man/ubicoin-cli.1
  doc/man/ubicoin-qt.1
  doc/man/ubicoin-tx.1
  doc/man/ubicoind.1
  src/qt/intro.cpp
Labels: enhancement

#4 Make it easier to specify gbuild resource limits
  doc/release-process.md
Labels: documentation, enhancement

#5 Update minimumchainwork, and getchaintxstats
  src/chainparams.cpp
Labels: Update

#6 Pul master to v0.17.1.3
  README.md
  contrib/seeds/nodes_main.txt
  contrib/seeds/nodes_test.txt
  doc/build-netbsd.md
  doc/build-openbsd.md
  doc/gitian-building.md
  src/chainparams.cpp
  src/chainparamsseeds.h
Labels: Update
